// <auto-generated />
namespace Hospital.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class a62 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a62));
        
        string IMigrationMetadata.Id
        {
            get { return "201906221436490_a62"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
